// <auto-generated />
using System;
using Commission.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commission.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commission.Entities.CommissionEntity", b =>
                {
                    b.Property<Guid>("commissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameOfCommission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("presidentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("commissionId");

                    b.HasIndex("presidentId");

                    b.ToTable("Commission");

                    b.HasData(
                        new
                        {
                            commissionId = new Guid("03dcf963-9569-4773-ae05-f205a97ffcc7"),
                            nameOfCommission = "First",
                            presidentId = new Guid("f5468f83-d3af-49df-8136-7d5323cad68b")
                        },
                        new
                        {
                            commissionId = new Guid("c4e35c57-addb-4c11-b476-dc91f9ff14a2"),
                            nameOfCommission = "Second",
                            presidentId = new Guid("f5468f83-d3af-49df-8136-7d5323cad68b")
                        },
                        new
                        {
                            commissionId = new Guid("4b7c8b4d-bcb1-433b-bd88-38ff0032caaf"),
                            nameOfCommission = "Third",
                            presidentId = new Guid("f5468f83-d3af-49df-8136-7d5323cad68b")
                        });
                });

            modelBuilder.Entity("Commission.Entities.MemberEntity", b =>
                {
                    b.Property<Guid>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("commissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("personalityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("memberId");

                    b.HasIndex("commissionId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            memberId = new Guid("1084e8c4-c92b-4ea3-9c20-0ca8bc8d5917"),
                            commissionId = new Guid("4b7c8b4d-bcb1-433b-bd88-38ff0032caaf"),
                            personalityId = new Guid("57029eb1-8c5f-4a55-824e-344a4df697ad")
                        },
                        new
                        {
                            memberId = new Guid("cf18da5d-07f3-4e56-90a2-03c8a9bde369"),
                            commissionId = new Guid("c4e35c57-addb-4c11-b476-dc91f9ff14a2"),
                            personalityId = new Guid("4a664b46-7959-4c8d-b830-618e3bea1aa2")
                        });
                });

            modelBuilder.Entity("Commission.Entities.PresidentEntity", b =>
                {
                    b.Property<Guid>("presidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("personalityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("presidentId");

                    b.ToTable("President");

                    b.HasData(
                        new
                        {
                            presidentId = new Guid("f5468f83-d3af-49df-8136-7d5323cad68b"),
                            personalityId = new Guid("274d5a86-9e8c-481a-bfac-7043db9ef65a")
                        },
                        new
                        {
                            presidentId = new Guid("2d31d380-627e-4cd8-b29a-76d21c6c65b3"),
                            personalityId = new Guid("916c6f7b-651b-440d-b811-7fe9e35d38ab")
                        },
                        new
                        {
                            presidentId = new Guid("99832b19-a420-4420-8fc9-10b22a7b0324"),
                            personalityId = new Guid("19e4a45d-0e40-42dc-b502-cd774f606e87")
                        });
                });

            modelBuilder.Entity("Commission.Entities.CommissionEntity", b =>
                {
                    b.HasOne("Commission.Entities.PresidentEntity", "president")
                        .WithMany()
                        .HasForeignKey("presidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("president");
                });

            modelBuilder.Entity("Commission.Entities.MemberEntity", b =>
                {
                    b.HasOne("Commission.Entities.CommissionEntity", "commission")
                        .WithMany()
                        .HasForeignKey("commissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commission");
                });
#pragma warning restore 612, 618
        }
    }
}
