// <auto-generated />
using System;
using Country.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Country.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Country.Entities.Address", b =>
                {
                    b.Property<Guid>("addressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zipCode")
                        .HasColumnType("int");

                    b.HasKey("addressId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            addressId = new Guid("0dc88d24-82a7-4aec-9464-0d06b9e119ca"),
                            place = "NS",
                            street = "Milosa Crnjanskog 4",
                            zipCode = 21000
                        });
                });

            modelBuilder.Entity("Country.Entities.Country1", b =>
                {
                    b.Property<Guid>("countryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameConuntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("countryId");

                    b.ToTable("Country1");

                    b.HasData(
                        new
                        {
                            countryId = new Guid("c1ba9fac-43fa-4502-9f93-d3f772dca929"),
                            nameConuntry = "Srbija"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
